### ISSUE TITLE
Complete auto rotation feature

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-tokenizer#11]
It appears to me that work was started on a feature that would automatically rotate tokenizers, but the feature is not operational. 

Additionally I note that during the provisional key deprecation code that the `CACHED_TOKENIZER` value is not properly evicted.

**Comment by dlongley** [comment]
`CACHED_TOKENIZER` is now properly evicted in `5.1.0`. Added a test to ensure the feature worked as well. Closing this issue because the feature works -- whether or not it is used is an application level decision. A call to `setAutoRotationChecker` should be all that is required.
